# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crm_giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import gspread
from crm_ara_ekran import *

credentials = 'log_utils.json'
gc = gspread.service_account(filename=credentials)
spreadsheet = gc.open('Kullanicilar')
worksheet = spreadsheet.get_worksheet(0)
all_values = worksheet.get_all_values()


class Giris(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.resize(606, 336)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 190, 171, 31))
        self.pushButton.setObjectName("pushButton")
        
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 70, 291, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 70, 151, 31))
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 141, 31))
        self.label_2.setObjectName("label_2")
        
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 120, 291, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        
        self.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        
        self.pushButton.clicked.connect(self.girisKontrol)
        self.Ara_Ekran=None
             
        self.setupUi()


    def setupUi(self):
        self.setWindowTitle( "Giris")
        self.pushButton.setText("Giris")
        self.label.setText("Kullanici Adiniz")
        self.label_2.setText( "Sifre")
        self.show()




    def girisKontrol(self):
        kullaniciAdi = self.lineEdit_3.text()
        sifre=self.lineEdit_4.text()
        kontrol=okGirisKontrol(kullaniciAdi,sifre,all_values)
        if kontrol:
            if self.Ara_Ekran is None:
                self.Ara_Ekran = Ara_Ekran()
                self.Ara_Ekran.onceki_pencere = self
            self.Ara_Ekran.show()
            self.hide()


def okGirisKontrol(kullaniciAdi,sifre,tumVeriler):
        kontrol=False
        for row in tumVeriler:
            if (kullaniciAdi==row[0]):
                if sifre==row[1]:
                    kontrol=True
        return kontrol



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = Giris()
    sys.exit(app.exec_())
